### ISSUE TITLE
building two separate parsers with pattern name overlaps causes name collisions

### ISSUE THREAD

**Issue by cheezman34** [andychase/reparse#2]
If two separate parsers share names for patterns, then building the second parser may cause it to incorrectly use the pattern from the first.  I think this problem may only surface with nested patterns.

This happens because patterns are added to expression_builder.type_db when building patterns, and because type_db is a class variable rather than an instance variable (meaning it will maintain all the cached patterns from the first build).  I think the solution should be as simple as removing `type_db = {}` from the body of builders.Expression_Builder and adding `self.type_db = {}` at the start of the **init** method.

**Comment by andychase** [comment]
Thanks for reporting this cheezman34. Gotta watch those mutable constructors in class declarations.

Resolved in fc0480f.
